import { ref } from 'vue' // ✅ WAJIB: ini untuk ref() bisa digunakan

import bg from '@/assets/static/logo_card.png'

import xgsa from '@/assets/static/product/olt/olt-V8208.png'
import xgsb from '@/assets/static/product/olt/olt-V5832xg.png'
import xgsc from '@/assets/static/product/switch/onu-v2724xt.png'
import xgsd from '@/assets/static/product/ont/ont-h840c.png'

import ga from '@/assets/static/product/switch/onu-d2008gpe.png'
import gb from '@/assets/static/product/olt/olt-V8106.png'
import gc from '@/assets/static/product/olt/olt-V8102.png'
import gd from '@/assets/static/product/olt/olt-V5816.png'
import ge from '@/assets/static/product/olt/olt-V5808.png'
import gf from '@/assets/static/product/olt/olt-V5804.png'
import gg from '@/assets/static/product/ont/ont-h660-gma.png'
import gh from '@/assets/static/product/ont/ont-h660nb.png'
import gi from '@/assets/static/product/ont/ont-h665.png'
import gj from '@/assets/static/product/switch/onu-d2224gp.png'
import gk from '@/assets/static/product/switch/D2224g.png'
import gl from '@/assets/static/product/switch/onu-v2724gg.png'

import sa from '@/assets/static/product/switch/switch-v-8610.png'
import sb from '@/assets/static/product/switch/switch-v-8607.png'
import sc from '@/assets/static/product/switch/switch-v-8605.png'
import sd from '@/assets/static/product/switch/l2-c2100.png'
import se from '@/assets/static/product/switch/l2-c2300.png'
import sf from '@/assets/static/product/switch/l3-m4000.png'
import sg from '@/assets/static/product/switch/l3-m3500.png'

// Data dummy produk
const products = ref([
  {
    id: 1,
    logo: bg,
    image: xgsa,
    category: 'XGS-Pon',
    subCategory: 'OLT',
    title: 'V8208',
    port: '64 port',
    textc: 'Multi-service chassis for FTTx deployments Full',
    descriptions: 'text dummy',
    fitur1: '3.2Tbps switching capacity with Full-dluplex',
    fitur2: '3.2Tbps switching capacity with Full-dluplex',
    fitur3: '875W (SFU x 2 + FAN x 2 + PSU_DC x 2 + IU_XGSPON8 x 6 + IU_10GE8 x 2)',
    fitur4: 'dump4',
    fitur5: 'dump5',
    fitur6: 'dump6',
    fitur7: 'dump7',
    fitur8: 'dump8',
    fitur9: 'dump9',
    fitur10: 'dump10',
    fitur11: 'dump11',
    fitur12: 'dump12',
    fitur13: 'dump13',
    fitur14: 'dump14',
    fitur15: 'dump15',
    fitur16: 'dump16',
    fitur17: 'dump17',
    fitur18: 'dump18',
    fitur19: 'dump19',
    fitur20: 'dump20',
    info: 'dump21',
    networkdiagram: xgsa,
  },
  {
    id: 2,
    logo: bg,
    image: xgsb,
    category: 'G-Pon',
    subCategory: 'ONU',
    title: 'V8209',
    port: '49 port XGSPON',
    textc: 'redundancy',
    descriptions: 'text dummy',
    fitur1: 'dump1',
    fitur2: 'dump2',
    fitur3: 'dump3',
    fitur4: 'dump4',
    fitur5: 'dump5',
    fitur6: 'dump6',
    fitur7: 'dump7',
    fitur8: 'dump8',
    fitur9: 'dump9',
    fitur10: 'dump10',
    fitur11: 'dump11',
    fitur12: 'dump12',
    fitur13: 'dump13',
    fitur14: 'dump14',
    fitur15: 'dump15',
    fitur16: 'dump16',
    fitur17: 'dump17',
    fitur18: 'dump18',
    fitur19: 'dump19',
    fitur20: 'dump20',
    info: 'dump21',
    networkdiagram: xgsa,
  },
  {
    id: 3,
    logo: bg,
    image: xgsc,
    category: 'XGS-Pon',
    subCategory: 'ONT',
    title: 'V8210',
    port: '50 port XGSPON',
    textc: 'text dummy',
    descriptions: 'text dummy',
    fitur1: 'dump1',
    fitur2: 'dump2',
    fitur3: 'dump3',
    fitur4: 'dump4',
    fitur5: 'dump5',
    fitur6: 'dump6',
    fitur7: 'dump7',
    fitur8: 'dump8',
    fitur9: 'dump9',
    fitur10: 'dump10',
    fitur11: 'dump11',
    fitur12: 'dump12',
    fitur13: 'dump13',
    fitur14: 'dump14',
    fitur15: 'dump15',
    fitur16: 'dump16',
    fitur17: 'dump17',
    fitur18: 'dump18',
    fitur19: 'dump19',
    fitur20: 'dump20',
    info: 'dump21',
    networkdiagram: xgsa,
  },
  {
    id: 4,
    logo: bg,
    image: xgsd,
    category: 'Switch',
    subCategory: 'CoreSwitch',
    title: 'V8211',
    port: '51 port XGSPON',
    textc: 'text dummy',
    descriptions: 'text dummy',
    fitur1: 'dump1',
    fitur2: 'dump2',
    fitur3: 'dump3',
    fitur4: 'dump4',
    fitur5: 'dump5',
    fitur6: 'dump6',
    fitur7: 'dump7',
    fitur8: 'dump8',
    fitur9: 'dump9',
    fitur10: 'dump10',
    fitur11: 'dump11',
    fitur12: 'dump12',
    fitur13: 'dump13',
    fitur14: 'dump14',
    fitur15: 'dump15',
    fitur16: 'dump16',
    fitur17: 'dump17',
    fitur18: 'dump18',
    fitur19: 'dump19',
    fitur20: 'dump20',
    info: 'dump21',
    networkdiagram: xgsa,
  },
  {
    id: 5,
    logo: bg,
    image: ga,
    category: 'Switch',
    subCategory: 'L2Switch',
    title: 'V8212',
    port: '52 port XGSPON',
    textc: 'text dummy',
    descriptions: 'text dummy',
    fitur1: 'dump1',
    fitur2: 'dump2',
    fitur3: 'dump3',
    fitur4: 'dump4',
    fitur5: 'dump5',
    fitur6: 'dump6',
    fitur7: 'dump7',
    fitur8: 'dump8',
    fitur9: 'dump9',
    fitur10: 'dump10',
    fitur11: 'dump11',
    fitur12: 'dump12',
    fitur13: 'dump13',
    fitur14: 'dump14',
    fitur15: 'dump15',
    fitur16: 'dump16',
    fitur17: 'dump17',
    fitur18: 'dump18',
    fitur19: 'dump19',
    fitur20: 'dump20',
    info: 'dump21',
    networkdiagram: xgsa,
  },
  {
    id: 6,
    logo: bg,
    image: gb,
    category: 'Switch',
    subCategory: 'L3Switch',
    title: 'V8213',
    port: '53 port XGSPON',
    textc: 'text dummy',
    descriptions: 'text dummy',
    fitur1: 'dump1',
    fitur2: 'dump2',
    fitur3: 'dump3',
    fitur4: 'dump4',
    fitur5: 'dump5',
    fitur6: 'dump6',
    fitur7: 'dump7',
    fitur8: 'dump8',
    fitur9: 'dump9',
    fitur10: 'dump10',
    fitur11: 'dump11',
    fitur12: 'dump12',
    fitur13: 'dump13',
    fitur14: 'dump14',
    fitur15: 'dump15',
    fitur16: 'dump16',
    fitur17: 'dump17',
    fitur18: 'dump18',
    fitur19: 'dump19',
    fitur20: 'dump20',
    info: 'dump21',
    networkdiagram: xgsa,
  },
  {
    id: 7,
    logo: bg,
    image: gc,
    category: 'G-Pon',
    subCategory: 'OLT',
    title: 'V8214',
    port: '54 port XGSPON',
    textc: 'text dummy',
    descriptions: 'text dummy',
    fitur1: 'dump1',
    fitur2: 'dump2',
    fitur3: 'dump3',
    fitur4: 'dump4',
    fitur5: 'dump5',
    fitur6: 'dump6',
    fitur7: 'dump7',
    fitur8: 'dump8',
    fitur9: 'dump9',
    fitur10: 'dump10',
    fitur11: 'dump11',
    fitur12: 'dump12',
    fitur13: 'dump13',
    fitur14: 'dump14',
    fitur15: 'dump15',
    fitur16: 'dump16',
    fitur17: 'dump17',
    fitur18: 'dump18',
    fitur19: 'dump19',
    fitur20: 'dump20',
    info: 'dump21',
    networkdiagram: xgsa,
  },
  {
    id: 8,
    logo: bg,
    image: gd,
    category: 'XGS-Pon',
    subCategory: 'ONU',
    title: 'V8215',
    port: '55 port XGSPON',
    textc: 'text dummy',
    descriptions: 'text dummy',
    fitur1: 'dump1',
    fitur2: 'dump2',
    fitur3: 'dump3',
    fitur4: 'dump4',
    fitur5: 'dump5',
    fitur6: 'dump6',
    fitur7: 'dump7',
    fitur8: 'dump8',
    fitur9: 'dump9',
    fitur10: 'dump10',
    fitur11: 'dump11',
    fitur12: 'dump12',
    fitur13: 'dump13',
    fitur14: 'dump14',
    fitur15: 'dump15',
    fitur16: 'dump16',
    fitur17: 'dump17',
    fitur18: 'dump18',
    fitur19: 'dump19',
    fitur20: 'dump20',
    info: 'dump21',
    networkdiagram: xgsa,
  },
  {
    id: 9,
    logo: bg,
    image: ge,
    category: 'XGS-Pon',
    subCategory: 'ONT',
    title: 'V8216',
    port: '56 port XGSPON',
    textc: 'text dummy',
    descriptions: 'text dummy',
    fitur1: 'dump1',
    fitur2: 'dump2',
    fitur3: 'dump3',
    fitur4: 'dump4',
    fitur5: 'dump5',
    fitur6: 'dump6',
    fitur7: 'dump7',
    fitur8: 'dump8',
    fitur9: 'dump9',
    fitur10: 'dump10',
    fitur11: 'dump11',
    fitur12: 'dump12',
    fitur13: 'dump13',
    fitur14: 'dump14',
    fitur15: 'dump15',
    fitur16: 'dump16',
    fitur17: 'dump17',
    fitur18: 'dump18',
    fitur19: 'dump19',
    fitur20: 'dump20',
    info: 'dump21',
    networkdiagram: xgsa,
  },
  {
    id: 10,
    logo: bg,
    image: gf,
    category: 'Switch',
    subCategory: 'CoreSwitch',
    title: 'V8217',
    port: '57 port XGSPON',
    textc: 'text dummy',
    descriptions: 'text dummy',
    fitur1: 'dump1',
    fitur2: 'dump2',
    fitur3: 'dump3',
    fitur4: 'dump4',
    fitur5: 'dump5',
    fitur6: 'dump6',
    fitur7: 'dump7',
    fitur8: 'dump8',
    fitur9: 'dump9',
    fitur10: 'dump10',
    fitur11: 'dump11',
    fitur12: 'dump12',
    fitur13: 'dump13',
    fitur14: 'dump14',
    fitur15: 'dump15',
    fitur16: 'dump16',
    fitur17: 'dump17',
    fitur18: 'dump18',
    fitur19: 'dump19',
    fitur20: 'dump20',
    info: 'dump21',
    networkdiagram: xgsa,
  },
  {
    id: 11,
    logo: bg,
    image: gg,
    category: 'Switch',
    subCategory: 'L2Switch',
    title: 'V8218',
    port: '58 port XGSPON',
    textc: 'text dummy',
    descriptions: 'text dummy',
    fitur1: 'dump1',
    fitur2: 'dump2',
    fitur3: 'dump3',
    fitur4: 'dump4',
    fitur5: 'dump5',
    fitur6: 'dump6',
    fitur7: 'dump7',
    fitur8: 'dump8',
    fitur9: 'dump9',
    fitur10: 'dump10',
    fitur11: 'dump11',
    fitur12: 'dump12',
    fitur13: 'dump13',
    fitur14: 'dump14',
    fitur15: 'dump15',
    fitur16: 'dump16',
    fitur17: 'dump17',
    fitur18: 'dump18',
    fitur19: 'dump19',
    fitur20: 'dump20',
    info: 'dump21',
    networkdiagram: xgsa,
  },
  {
    id: 12,
    logo: bg,
    image: gh,
    category: 'Switch',
    subCategory: 'L3Switch',
    title: 'V8219',
    port: '59 port XGSPON',
    textc: 'text dummy',
    descriptions: 'text dummy',
    fitur1: 'dump1',
    fitur2: 'dump2',
    fitur3: 'dump3',
    fitur4: 'dump4',
    fitur5: 'dump5',
    fitur6: 'dump6',
    fitur7: 'dump7',
    fitur8: 'dump8',
    fitur9: 'dump9',
    fitur10: 'dump10',
    fitur11: 'dump11',
    fitur12: 'dump12',
    fitur13: 'dump13',
    fitur14: 'dump14',
    fitur15: 'dump15',
    fitur16: 'dump16',
    fitur17: 'dump17',
    fitur18: 'dump18',
    fitur19: 'dump19',
    fitur20: 'dump20',
    info: 'dump21',
    networkdiagram: xgsa,
  },
  {
    id: 13,
    logo: bg,
    image: gi,
    category: 'WiFi',
    subCategory: 'Controller',
    title: 'V8220',
    port: '60 port XGSPON',
    textc: 'text dummy',
    descriptions: 'text dummy',
    fitur1: 'dump1',
    fitur2: 'dump2',
    fitur3: 'dump3',
    fitur4: 'dump4',
    fitur5: 'dump5',
    fitur6: 'dump6',
    fitur7: 'dump7',
    fitur8: 'dump8',
    fitur9: 'dump9',
    fitur10: 'dump10',
    fitur11: 'dump11',
    fitur12: 'dump12',
    fitur13: 'dump13',
    fitur14: 'dump14',
    fitur15: 'dump15',
    fitur16: 'dump16',
    fitur17: 'dump17',
    fitur18: 'dump18',
    fitur19: 'dump19',
    fitur20: 'dump20',
    info: 'dump21',
    networkdiagram: xgsa,
  },
  {
    id: 14,
    logo: bg,
    image: gj,
    category: 'WiFi',
    subCategory: 'Access Point',
    title: 'V8221',
    port: '61 port XGSPON',
    textc: 'text dummy',
    descriptions: 'text dummy',
    fitur1: 'dump1',
    fitur2: 'dump2',
    fitur3: 'dump3',
    fitur4: 'dump4',
    fitur5: 'dump5',
    fitur6: 'dump6',
    fitur7: 'dump7',
    fitur8: 'dump8',
    fitur9: 'dump9',
    fitur10: 'dump10',
    fitur11: 'dump11',
    fitur12: 'dump12',
    fitur13: 'dump13',
    fitur14: 'dump14',
    fitur15: 'dump15',
    fitur16: 'dump16',
    fitur17: 'dump17',
    fitur18: 'dump18',
    fitur19: 'dump19',
    fitur20: 'dump20',
    info: 'dump21',
    networkdiagram: xgsa,
  },
  {
    id: 15,
    logo: bg,
    image: gk,
    category: 'WiFi',
    subCategory: 'Controller',
    title: 'V8221',
    port: '61 port XGSPON',
    textc: 'text dummy',
    descriptions: 'text dummy',
    fitur1: 'dump1',
    fitur2: 'dump2',
    fitur3: 'dump3',
    fitur4: 'dump4',
    fitur5: 'dump5',
    fitur6: 'dump6',
    fitur7: 'dump7',
    fitur8: 'dump8',
    fitur9: 'dump9',
    fitur10: 'dump10',
    fitur11: 'dump11',
    fitur12: 'dump12',
    fitur13: 'dump13',
    fitur14: 'dump14',
    fitur15: 'dump15',
    fitur16: 'dump16',
    fitur17: 'dump17',
    fitur18: 'dump18',
    fitur19: 'dump19',
    fitur20: 'dump20',
    info: 'dump21',
    networkdiagram: xgsa,
  },
  {
    id: 16,
    logo: bg,
    image: gl,
    category: 'WiFi',
    subCategory: 'Access Point',
    title: 'V8221',
    port: '61 port XGSPON',
    textc: 'text dummy',
    descriptions: 'text dummy',
    fitur1: 'dump1',
    fitur2: 'dump2',
    fitur3: 'dump3',
    fitur4: 'dump4',
    fitur5: 'dump5',
    fitur6: 'dump6',
    fitur7: 'dump7',
    fitur8: 'dump8',
    fitur9: 'dump9',
    fitur10: 'dump10',
    fitur11: 'dump11',
    fitur12: 'dump12',
    fitur13: 'dump13',
    fitur14: 'dump14',
    fitur15: 'dump15',
    fitur16: 'dump16',
    fitur17: 'dump17',
    fitur18: 'dump18',
    fitur19: 'dump19',
    fitur20: 'dump20',
    info: 'dump21',
    networkdiagram: xgsa,
  },
])

export default products

export function useProductById(id) {
  return products.value.find((c) => c.id === parseInt(id))
}
