import { ref } from 'vue' // ✅ WAJIB: ini untuk ref() bisa digunakan

import bg from '@/assets/static/logo_card.png'

import xgsa from '@/assets/static/product/olt/olt-V8208.png'
import xgsb from '@/assets/static/product/olt/olt-V5832xg.png'
import xgsc from '@/assets/static/product/switch/onu-v2724xt.png'
import xgsd from '@/assets/static/product/ont/ont-h840c.png'

import ga from '@/assets/static/product/switch/onu-d2008gpe.png'
import gb from '@/assets/static/product/olt/olt-V8106.png'
import gc from '@/assets/static/product/olt/olt-V8102.png'
import gd from '@/assets/static/product/olt/olt-V5816.png'
import ge from '@/assets/static/product/olt/olt-V5808.png'
import gf from '@/assets/static/product/olt/olt-V5804.png'
import gg from '@/assets/static/product/ont/ont-h660-gma.png'
import gh from '@/assets/static/product/ont/ont-h660nb.png'
import gi from '@/assets/static/product/ont/ont-h665.png'
import gj from '@/assets/static/product/switch/onu-d2224gp.png'
import gk from '@/assets/static/product/switch/D2224g.png'
import gl from '@/assets/static/product/switch/onu-v2724gg.png'

import sa from '@/assets/static/product/switch/switch-v-8610.png'
import sb from '@/assets/static/product/switch/switch-v-8607.png'
import sc from '@/assets/static/product/switch/switch-v-8605.png'
import sd from '@/assets/static/product/switch/l2-c2100.png'
import se from '@/assets/static/product/switch/l2-c2300.png'
import sf from '@/assets/static/product/switch/l3-m4000.png'
import sg from '@/assets/static/product/switch/l3-m3500.png'

// Data dummy produk
const products = ref([
  {
    id: 1,
    logo: bg,
    category: 'XGS-PON OLT',
    title: 'V8208 XGS-PON OLT',
    image: xgsa,
    port: '48 port XGSPON',
    textc: null,
    SwitchingCapacity: null,
    PacketForwarding: null,
    MACAddressTable: null,
    PoEBudget: null,
    JumboFrame: null,
    dimensions: '96 port GPON',
    PowerConsumption: null,
    descriptions: null,
    fitur1: null,
    fitur2: null,
    fitur3: null,
    fitur4: null,
    fitur5: null,
    fitur6: null,
    fitur7: null,
    fitur9: null,
    fitur10: null,
    fitur11: null,
    fitur12: null,
    fitur13: null,
    fitur14: null,
    fitur15: null,
    fitur16: null,
    fitur17: null,
    fitur18: null,
    fitur19: null,
    fitur20: null,
    info: null,
    environment1: null,
    environment2: null,
    environment3: null,
    environment4: null,
    environment5: null,
  },
  {
    id: 2,
    logo: bg,
    category: 'XGS-PON OLT',
    title: 'V5832XG XGS-PON OLT',
    image: xgsb,
    port: '16 port XGSPON',
    textc: null,
    SwitchingCapacity: null,
    PacketForwarding: null,
    MACAddressTable: null,
    PoEBudget: null,
    JumboFrame: null,
    dimensions: '96 port GPON',
    PowerConsumption: null,
    descriptions: null,
    fitur1: null,
    fitur2: null,
    fitur3: null,
    fitur4: null,
    fitur5: null,
    fitur6: null,
    fitur7: null,
    fitur9: null,
    fitur10: null,
    fitur11: null,
    fitur12: null,
    fitur13: null,
    fitur14: null,
    fitur15: null,
    fitur16: null,
    fitur17: null,
    fitur18: null,
    fitur19: null,
    fitur20: null,
    info: null,
    environment1: null,
    environment2: null,
    environment3: null,
    environment4: null,
    environment5: null,
  },
  {
    id: 3,
    logo: bg,
    category: 'XGS-PON ONU',
    title: 'V2724XT XGS-PON ONU',
    image: xgsc,
    port: '24 port 10G RJ45',
    textc: null,
    SwitchingCapacity: null,
    PacketForwarding: null,
    MACAddressTable: null,
    PoEBudget: null,
    JumboFrame: null,
    dimensions: '96 port GPON',
    PowerConsumption: null,
    descriptions: null,
    fitur1: null,
    fitur2: null,
    fitur3: null,
    fitur4: null,
    fitur5: null,
    fitur6: null,
    fitur7: null,
    fitur9: null,
    fitur10: null,
    fitur11: null,
    fitur12: null,
    fitur13: null,
    fitur14: null,
    fitur15: null,
    fitur16: null,
    fitur17: null,
    fitur18: null,
    fitur19: null,
    fitur20: null,
    info: null,
    environment1: null,
    environment2: null,
    environment3: null,
    environment4: null,
    environment5: null,
  },
  {
    id: 4,
    logo: bg,
    category: 'XGS-PON ONT',
    title: 'H840C XGS-PON ONT',
    image: xgsd,
    port: '4xGE RJ45',
    textc: null,
    SwitchingCapacity: null,
    PacketForwarding: null,
    MACAddressTable: null,
    PoEBudget: null,
    JumboFrame: null,
    dimensions: '96 port GPON',
    PowerConsumption: null,
    descriptions: null,
    fitur1: null,
    fitur2: null,
    fitur3: null,
    fitur4: null,
    fitur5: null,
    fitur6: null,
    fitur7: null,
    fitur9: null,
    fitur10: null,
    fitur11: null,
    fitur12: null,
    fitur13: null,
    fitur14: null,
    fitur15: null,
    fitur16: null,
    fitur17: null,
    fitur18: null,
    fitur19: null,
    fitur20: null,
    info: null,
    environment1: null,
    environment2: null,
    environment3: null,
    environment4: null,
    environment5: null,
  },
  {
    id: 5,
    logo: bg,
    category: 'G-PON ONU/PoE',
    title: 'D2008GPE G-PON ONU/PoE',
    image: ga,
    port: '8 port PoE',
    textc: null,
    SwitchingCapacity: null,
    PacketForwarding: null,
    MACAddressTable: null,
    PoEBudget: null,
    JumboFrame: null,
    dimensions: '96 port GPON',
    PowerConsumption: null,
    descriptions: null,
    fitur1: null,
    fitur2: null,
    fitur3: null,
    fitur4: null,
    fitur5: null,
    fitur6: null,
    fitur7: null,
    fitur9: null,
    fitur10: null,
    fitur11: null,
    fitur12: null,
    fitur13: null,
    fitur14: null,
    fitur15: null,
    fitur16: null,
    fitur17: null,
    fitur18: null,
    fitur19: null,
    fitur20: null,
    info: null,
    environment1: null,
    environment2: null,
    environment3: null,
    environment4: null,
    environment5: null,
  },
  {
    id: 6,
    logo: bg,
    category: 'G-PON OLT',
    title: 'V-8106 G-PON OLT',
    image: gb,
    port: '96 port GPON',
    textc: null,
    SwitchingCapacity: null,
    PacketForwarding: null,
    MACAddressTable: null,
    PoEBudget: null,
    JumboFrame: null,
    dimensions: '96 port GPON',
    PowerConsumption: null,
    descriptions: null,
    fitur1: null,
    fitur2: null,
    fitur3: null,
    fitur4: null,
    fitur5: null,
    fitur6: null,
    fitur7: null,
    fitur9: null,
    fitur10: null,
    fitur11: null,
    fitur12: null,
    fitur13: null,
    fitur14: null,
    fitur15: null,
    fitur16: null,
    fitur17: null,
    fitur18: null,
    fitur19: null,
    fitur20: null,
    info: null,
    environment1: null,
    environment2: null,
    environment3: null,
    environment4: null,
    environment5: null,
  },
  {
    id: 7,
    logo: bg,
    category: 'G-PON OLT',
    title: 'V-8102 G-PON OLT',
    image: gc,
    port: '32 port GPON',
    textc: null,
    SwitchingCapacity: null,
    PacketForwarding: null,
    MACAddressTable: null,
    PoEBudget: null,
    JumboFrame: null,
    dimensions: '96 port GPON',
    PowerConsumption: null,
    descriptions: null,
    fitur1: null,
    fitur2: null,
    fitur3: null,
    fitur4: null,
    fitur5: null,
    fitur6: null,
    fitur7: null,
    fitur9: null,
    fitur10: null,
    fitur11: null,
    fitur12: null,
    fitur13: null,
    fitur14: null,
    fitur15: null,
    fitur16: null,
    fitur17: null,
    fitur18: null,
    fitur19: null,
    fitur20: null,
    info: null,
    environment1: null,
    environment2: null,
    environment3: null,
    environment4: null,
    environment5: null,
  },
  {
    id: 8,
    logo: bg,
    category: 'G-PON OLT',
    title: 'V5816 G-PON OLT',
    image: gd,
    port: '16 port GPON',
    textc: null,
    SwitchingCapacity: null,
    PacketForwarding: null,
    MACAddressTable: null,
    PoEBudget: null,
    JumboFrame: null,
    dimensions: '96 port GPON',
    PowerConsumption: null,
    descriptions: null,
    fitur1: null,
    fitur2: null,
    fitur3: null,
    fitur4: null,
    fitur5: null,
    fitur6: null,
    fitur7: null,
    fitur9: null,
    fitur10: null,
    fitur11: null,
    fitur12: null,
    fitur13: null,
    fitur14: null,
    fitur15: null,
    fitur16: null,
    fitur17: null,
    fitur18: null,
    fitur19: null,
    fitur20: null,
    info: null,
    environment1: null,
    environment2: null,
    environment3: null,
    environment4: null,
    environment5: null,
  },
  {
    id: 9,
    logo: bg,
    category: 'G-PON OLT',
    title: 'V5808 G-PON OLT',
    image: ge,
    port: '8 port GPON',
    textc: null,
    SwitchingCapacity: null,
    PacketForwarding: null,
    MACAddressTable: null,
    PoEBudget: null,
    JumboFrame: null,
    dimensions: '96 port GPON',
    PowerConsumption: null,
    descriptions: null,
    fitur1: null,
    fitur2: null,
    fitur3: null,
    fitur4: null,
    fitur5: null,
    fitur6: null,
    fitur7: null,
    fitur9: null,
    fitur10: null,
    fitur11: null,
    fitur12: null,
    fitur13: null,
    fitur14: null,
    fitur15: null,
    fitur16: null,
    fitur17: null,
    fitur18: null,
    fitur19: null,
    fitur20: null,
    info: null,
    environment1: null,
    environment2: null,
    environment3: null,
    environment4: null,
    environment5: null,
  },
  {
    id: 10,
    logo: bg,
    category: 'G-PON OLT',
    title: 'V5804 G-PON OLT',
    image: gf,
    port: '4 port GPON',
    textc: null,
    SwitchingCapacity: null,
    PacketForwarding: null,
    MACAddressTable: null,
    PoEBudget: null,
    JumboFrame: null,
    dimensions: '96 port GPON',
    PowerConsumption: null,
    descriptions: null,
    fitur1: null,
    fitur2: null,
    fitur3: null,
    fitur4: null,
    fitur5: null,
    fitur6: null,
    fitur7: null,
    fitur9: null,
    fitur10: null,
    fitur11: null,
    fitur12: null,
    fitur13: null,
    fitur14: null,
    fitur15: null,
    fitur16: null,
    fitur17: null,
    fitur18: null,
    fitur19: null,
    fitur20: null,
    info: null,
    environment1: null,
    environment2: null,
    environment3: null,
    environment4: null,
    environment5: null,
  },
  {
    id: 11,
    logo: bg,
    category: 'G-PON ONT',
    title: 'H660-GMA G-PON ONT',
    image: gg,
    port: '4xGE RJ45',
    textc: null,
    SwitchingCapacity: null,
    PacketForwarding: null,
    MACAddressTable: null,
    PoEBudget: null,
    JumboFrame: null,
    dimensions: '96 port GPON',
    PowerConsumption: null,
    descriptions: null,
    fitur1: null,
    fitur2: null,
    fitur3: null,
    fitur4: null,
    fitur5: null,
    fitur6: null,
    fitur7: null,
    fitur9: null,
    fitur10: null,
    fitur11: null,
    fitur12: null,
    fitur13: null,
    fitur14: null,
    fitur15: null,
    fitur16: null,
    fitur17: null,
    fitur18: null,
    fitur19: null,
    fitur20: null,
    info: null,
    environment1: null,
    environment2: null,
    environment3: null,
    environment4: null,
    environment5: null,
  },
  {
    id: 12,
    logo: bg,
    category: 'G-PON ONT',
    title: 'H660NB G-PON ONT',
    image: gh,
    port: '4xGE RJ45',
    textc: null,
    SwitchingCapacity: null,
    PacketForwarding: null,
    MACAddressTable: null,
    PoEBudget: null,
    JumboFrame: null,
    dimensions: '96 port GPON',
    PowerConsumption: null,
    descriptions: null,
    fitur1: null,
    fitur2: null,
    fitur3: null,
    fitur4: null,
    fitur5: null,
    fitur6: null,
    fitur7: null,
    fitur9: null,
    fitur10: null,
    fitur11: null,
    fitur12: null,
    fitur13: null,
    fitur14: null,
    fitur15: null,
    fitur16: null,
    fitur17: null,
    fitur18: null,
    fitur19: null,
    fitur20: null,
    info: null,
    environment1: null,
    environment2: null,
    environment3: null,
    environment4: null,
    environment5: null,
  },
  {
    id: 13,
    logo: bg,
    category: 'G-PON ONT',
    title: 'H665 G-PON ONT',
    image: gi,
    port: '1xGE RJ45',
    textc: null,
    SwitchingCapacity: null,
    PacketForwarding: null,
    MACAddressTable: null,
    PoEBudget: null,
    JumboFrame: null,
    dimensions: '96 port GPON',
    PowerConsumption: null,
    descriptions: null,
    fitur1: null,
    fitur2: null,
    fitur3: null,
    fitur4: null,
    fitur5: null,
    fitur6: null,
    fitur7: null,
    fitur9: null,
    fitur10: null,
    fitur11: null,
    fitur12: null,
    fitur13: null,
    fitur14: null,
    fitur15: null,
    fitur16: null,
    fitur17: null,
    fitur18: null,
    fitur19: null,
    fitur20: null,
    info: null,
    environment1: null,
    environment2: null,
    environment3: null,
    environment4: null,
    environment5: null,
  },
  {
    id: 14,
    logo: bg,
    category: 'G-PON ONU/PoE',
    title: 'D2224GP G-PON ONU/PoE',
    image: gj,
    port: '24 port PoE',
    textc: null,
    SwitchingCapacity: null,
    PacketForwarding: null,
    MACAddressTable: null,
    PoEBudget: null,
    JumboFrame: null,
    dimensions: '96 port GPON',
    PowerConsumption: null,
    descriptions: null,
    fitur1: null,
    fitur2: null,
    fitur3: null,
    fitur4: null,
    fitur5: null,
    fitur6: null,
    fitur7: null,
    fitur9: null,
    fitur10: null,
    fitur11: null,
    fitur12: null,
    fitur13: null,
    fitur14: null,
    fitur15: null,
    fitur16: null,
    fitur17: null,
    fitur18: null,
    fitur19: null,
    fitur20: null,
    info: null,
    environment1: null,
    environment2: null,
    environment3: null,
    environment4: null,
    environment5: null,
  },
  {
    id: 15,
    logo: bg,
    category: 'G-PON ONU/PoE',
    title: 'D2224G G-PON ONU',
    image: gk,
    port: '24 port RJ45',
    textc: null,
    SwitchingCapacity: null,
    PacketForwarding: null,
    MACAddressTable: null,
    PoEBudget: null,
    JumboFrame: null,
    dimensions: '96 port GPON',
    PowerConsumption: null,
    descriptions: null,
    fitur1: null,
    fitur2: null,
    fitur3: null,
    fitur4: null,
    fitur5: null,
    fitur6: null,
    fitur7: null,
    fitur9: null,
    fitur10: null,
    fitur11: null,
    fitur12: null,
    fitur13: null,
    fitur14: null,
    fitur15: null,
    fitur16: null,
    fitur17: null,
    fitur18: null,
    fitur19: null,
    fitur20: null,
    info: null,
    environment1: null,
    environment2: null,
    environment3: null,
    environment4: null,
    environment5: null,
  },
  {
    id: 16,
    logo: bg,
    category: 'G-PON ONU/PoE',
    title: 'V2724GG G-PON ONU',
    image: gl,
    port: '24 port 1G SFP',
    textc: null,
    SwitchingCapacity: null,
    PacketForwarding: null,
    MACAddressTable: null,
    PoEBudget: null,
    JumboFrame: null,
    dimensions: '96 port GPON',
    PowerConsumption: null,
    descriptions: null,
    fitur1: null,
    fitur2: null,
    fitur3: null,
    fitur4: null,
    fitur5: null,
    fitur6: null,
    fitur7: null,
    fitur9: null,
    fitur10: null,
    fitur11: null,
    fitur12: null,
    fitur13: null,
    fitur14: null,
    fitur15: null,
    fitur16: null,
    fitur17: null,
    fitur18: null,
    fitur19: null,
    fitur20: null,
    info: null,
    environment1: null,
    environment2: null,
    environment3: null,
    environment4: null,
    environment5: null,
  },
  {
    id: 17,
    logo: bg,
    category: 'Core Switch',
    title: 'V-8610 Core Switch',
    image: sa,
    port: '96x40G/100G',
    textc: null,
    SwitchingCapacity: null,
    PacketForwarding: null,
    MACAddressTable: null,
    PoEBudget: null,
    JumboFrame: null,
    dimensions: '96 port GPON',
    PowerConsumption: null,
    descriptions: null,
    fitur1: null,
    fitur2: null,
    fitur3: null,
    fitur4: null,
    fitur5: null,
    fitur6: null,
    fitur7: null,
    fitur9: null,
    fitur10: null,
    fitur11: null,
    fitur12: null,
    fitur13: null,
    fitur14: null,
    fitur15: null,
    fitur16: null,
    fitur17: null,
    fitur18: null,
    fitur19: null,
    fitur20: null,
    info: null,
    environment1: null,
    environment2: null,
    environment3: null,
    environment4: null,
    environment5: null,
  },
  {
    id: 18,
    logo: bg,
    category: 'Core Switch',
    title: 'V-8607 Core Switch',
    image: sb,
    port: '60x40G/100G',
    textc: null,
    SwitchingCapacity: null,
    PacketForwarding: null,
    MACAddressTable: null,
    PoEBudget: null,
    JumboFrame: null,
    dimensions: '96 port GPON',
    PowerConsumption: null,
    descriptions: null,
    fitur1: null,
    fitur2: null,
    fitur3: null,
    fitur4: null,
    fitur5: null,
    fitur6: null,
    fitur7: null,
    fitur9: null,
    fitur10: null,
    fitur11: null,
    fitur12: null,
    fitur13: null,
    fitur14: null,
    fitur15: null,
    fitur16: null,
    fitur17: null,
    fitur18: null,
    fitur19: null,
    fitur20: null,
    info: null,
    environment1: null,
    environment2: null,
    environment3: null,
    environment4: null,
    environment5: null,
  },
  {
    id: 19,
    logo: bg,
    category: 'Core Switch',
    title: 'V-8605 Core Switch',
    image: sc,
    port: '36x40G',
    textc: null,
    SwitchingCapacity: null,
    PacketForwarding: null,
    MACAddressTable: null,
    PoEBudget: null,
    JumboFrame: null,
    dimensions: '96 port GPON',
    PowerConsumption: null,
    descriptions: null,
    fitur1: null,
    fitur2: null,
    fitur3: null,
    fitur4: null,
    fitur5: null,
    fitur6: null,
    fitur7: null,
    fitur9: null,
    fitur10: null,
    fitur11: null,
    fitur12: null,
    fitur13: null,
    fitur14: null,
    fitur15: null,
    fitur16: null,
    fitur17: null,
    fitur18: null,
    fitur19: null,
    fitur20: null,
    info: null,
    environment1: null,
    environment2: null,
    environment3: null,
    environment4: null,
    environment5: null,
  },
  {
    id: 20,
    logo: bg,
    category: 'L2 Switch',
    title: 'L2-C2100 L2 Switch',
    image: sd,
    port: '2 x 1/10GBase-R (SFP/SFP+) 8 x 10/25GBase-R (SFP+/SFP28) 2 x 100GBase-R (QSFP28) or 1 x 100GBase-R (QSFP-DD)',
    textc: null,
    SwitchingCapacity: null,
    PacketForwarding: null,
    MACAddressTable: null,
    PoEBudget: null,
    JumboFrame: null,
    dimensions: '96 port GPON',
    PowerConsumption: null,
    descriptions: null,
    fitur1: null,
    fitur2: null,
    fitur3: null,
    fitur4: null,
    fitur5: null,
    fitur6: null,
    fitur7: null,
    fitur9: null,
    fitur10: null,
    fitur11: null,
    fitur12: null,
    fitur13: null,
    fitur14: null,
    fitur15: null,
    fitur16: null,
    fitur17: null,
    fitur18: null,
    fitur19: null,
    fitur20: null,
    info: null,
    environment1: null,
    environment2: null,
    environment3: null,
    environment4: null,
    environment5: null,
  },
  {
    id: 21,
    logo: bg,
    category: 'L2 Switch',
    title: 'L2-C2300 L2 Switch',
    image: se,
    port: '4 x 1/10GBase-R (SFP/SFP+) 16 x 10/25GBase-R (SFP+/SFP28) 6 x 100GBase-R (QSFP28/QSFP-DD)',
    textc: null,
    SwitchingCapacity: null,
    PacketForwarding: null,
    MACAddressTable: null,
    PoEBudget: null,
    JumboFrame: null,
    dimensions: '96 port GPON',
    PowerConsumption: null,
    descriptions: null,
    fitur1: null,
    fitur2: null,
    fitur3: null,
    fitur4: null,
    fitur5: null,
    fitur6: null,
    fitur7: null,
    fitur9: null,
    fitur10: null,
    fitur11: null,
    fitur12: null,
    fitur13: null,
    fitur14: null,
    fitur15: null,
    fitur16: null,
    fitur17: null,
    fitur18: null,
    fitur19: null,
    fitur20: null,
    info: null,
    environment1: null,
    environment2: null,
    environment3: null,
    environment4: null,
    environment5: null,
  },
  {
    id: 22,
    logo: bg,
    category: 'L3 Switch',
    title: 'L3-M4000 L3 Switch',
    image: sf,
    port: '32 port 1/10/25GBase-R (SFP28)',
    textc: null,
    SwitchingCapacity: null,
    PacketForwarding: null,
    MACAddressTable: null,
    PoEBudget: null,
    JumboFrame: null,
    dimensions: '96 port GPON',
    PowerConsumption: null,
    descriptions: null,
    fitur1: null,
    fitur2: null,
    fitur3: null,
    fitur4: null,
    fitur5: null,
    fitur6: null,
    fitur7: null,
    fitur9: null,
    fitur10: null,
    fitur11: null,
    fitur12: null,
    fitur13: null,
    fitur14: null,
    fitur15: null,
    fitur16: null,
    fitur17: null,
    fitur18: null,
    fitur19: null,
    fitur20: null,
    info: null,
    environment1: null,
    environment2: null,
    environment3: null,
    environment4: null,
    environment5: null,
  },
  {
    id: 23,
    logo: bg,
    category: 'L3 Switch',
    title: 'L3-M3500 L3 Switch',
    image: sg,
    port: '48-port - 1GBase-R (SFP) or 10GBase-R (SFP+) or 25GBase-R (SFP28)',
    textc: null,
    SwitchingCapacity: null,
    PacketForwarding: null,
    MACAddressTable: null,
    PoEBudget: null,
    JumboFrame: null,
    dimensions: '96 port GPON',
    PowerConsumption: null,
    descriptions: null,
    fitur1: null,
    fitur2: null,
    fitur3: null,
    fitur4: null,
    fitur5: null,
    fitur6: null,
    fitur7: null,
    fitur9: null,
    fitur10: null,
    fitur11: null,
    fitur12: null,
    fitur13: null,
    fitur14: null,
    fitur15: null,
    fitur16: null,
    fitur17: null,
    fitur18: null,
    fitur19: null,
    fitur20: null,
    info: null,
    environment1: null,
    environment2: null,
    environment3: null,
    environment4: null,
    environment5: null,
  },
])

export default products

export function useProductById(id) {
  return products.value.find((c) => c.id === parseInt(id))
}
