import { ref } from 'vue' // ✅ WAJIB: ini untuk ref() bisa digunakan

function generateSlug(text) {
  return text
    .toLowerCase()
    .trim()
    .replace(/[^\w\s-]/g, '')
    .replace(/[\s_-]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

// Data dummy produk
const products = ref([
  {
    id: '1',
    module: 'A',
    logo: 'https://ik.imagekit.io/iamfake/products/logo_card.png?updatedAt=1750092485669',
    image: 'https://ik.imagekit.io/iamfake/products/olt-V8208.png?updatedAt=1750091720038',
    category: 'XGSPON',
    subCategory: 'OLT',
    title: 'V8208',
    subtitle: 'XGSPON OLT',
    spec1: '8p GPON/XGSPON Combo LC',
    spec2: '16p GPON/XGSPON Combo LC',
    spec3: '8p 10GE LC',
    spec4: 'DC',
    spec5: 'up to 96PON',
    spec6: '',
    spec7: '',
    descriptions:
      'The V8208 is a 6RU height chassis PON Optical Line Termination (OLT) supporting XGS-PON, GPON as well as 10GE Active Ethernet service. It terminates the traffic coming from the subscriber lines and consolidates it on one or more Gigabit Ethernet interfaces towards the metropolitan area. It is a high-density chassis system that supports up to 8,192 residential and business subscribers with 64 GPON ports (1:128 split ratio). It also provides simultaneous services of GPON and Gigabit Ethernet. V8208 features flexible and high capacity PON access and 10GE uplinks, scalability and line rate performance with a 3.2Tbps (Full -duplex) non-blocked switch fabric.',
    fitur1: '8-port GPON interfaces per slot',
    fitur2: '8-port XGS-PON interfaces per slot',
    fitur3: '8-port 10GE interface per slot',
    fitur4: 'Multi-service chassis for FTTx deployments Full redundancy',
    fitur5: 'Support and delivery of various service types',
    fitur6: 'VoIP, IP-TV, high-speed internet, mobile, etc',
    fitur7: 'Non-stop forwarding, Non-stop routing features based on distributed architecture',
    fitur8: 'Selective service/uplink modular units for flexible network',
    fitur9: 'High capacity XGS-PON access and 10GE uplink and line rate performance',
    fitur10: 'Realtime network traffic monitoring and analyzing',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '8MB(Boot) + 512MB(NOS)',
    sdrammemory: '4GB (DDR4)',
    Interface1: 'IU_GPON8 for GPON(SFP)',
    Interface2: 'IU_XGSPON8 for GPON/XGS-PON Combo(SFP+)',
    Interface3: 'IU_10GE8 for 10GE(SFP+)',
    Interface4: '',
    Antena: '',
    operatingtemperature: '0 ~ 50°C',
    storagetemperature: '-20 ~ 70°C',
    operatinghumidity: '20 ~ 80% (non-condensing)',
    power1: '-48VDC',
    power2: '',
    poweroptical: '',
    powercomsumptions: '875W (SFU x 2 + FAN x 2 + PSU_DC x 2 + IU_XGSPON8 x 6 + IU_10GE8 x 2)',
    dimensions: '443.8 x 265.9 x 280 mm (Wing Bracket excluded)',
    networkdiagram: '',
  },
  {
    id: '2',
    module: 'A',
    logo: 'https://ik.imagekit.io/iamfake/products/logo_card.png?updatedAt=1750092485669',
    image: 'https://ik.imagekit.io/iamfake/products/olt-V5832xg.png?updatedAt=1750091714791',
    category: 'XGSPON',
    subCategory: 'OLT',
    title: 'V5832XG',
    subtitle: 'XGSPON OLT',
    spec1: '8p GPON/XGSPON Combo LC',
    spec2: '16p GPON/XGSPON Combo LC',
    spec3: '8/16p GPON LC',
    spec4: '4p 10GE LC',
    spec5: 'AC/DC',
    spec6: 'up to 32PON',
    spec7: '',
    descriptions:
      'The V5832XG is a cost-effective chassis based PON Optical Line Termination (OLT). Based on the latest IEEE standard, the V5832XG has been specifically designed to fulfill a function within mobile backhaul networks. The V5832XG can be used for a variety of new, revenue-generating applications, for example as L2/L3 Ethernet LAN switches in high rise buildings or as datacenter application and aggregation switches. Additionally, the V5832XG system helps to enhance network efficiency through offering dedicated L3 functionality. The V5832XG introduces a point-to-multipoint concept with the PON technology, which enables a cost-effective FTTx service. The reason why PON is considered as a cost-effective solution is its usage of a passive splitter rather than an active switching system.',
    fitur1: '16-port GPON interfaces per slot',
    fitur2: '8-port XGS-PON interfaces per slot',
    fitur3: '8-port 10GE interfaces per slot',
    fitur4: '800Gbps switching capacity',
    fitur5: '595Mpps throughput',
    fitur6: 'Hot swappable for all plug-in units',
    fitur7: 'XGS-PON ODN class N1 compliant with ITU-T G.9807.1',
    fitur8: 'GPON SFP B+ compliant with ITU-T G.984.2',
    fitur9: 'GPON SFP C+ compliant with ITU-T G.984.2',
    fitur10: 'Supports DDM (Digital Diagnostics Monitoring)',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '8MB(Boot) + 512MB(NOS)',
    sdrammemory: '4GB (DDR4 with ECC)',
    Interface1: 'IU_GPON16 for GPON(SFP)',
    Interface2: 'IU_XGSPON8 for XGS-PON (SFP)',
    Interface3: 'IU_10GE4_UP for 10GE(SFP+)',
    Interface4: '',
    Antena: '',
    operatingtemperature: '10 ~ 50°C',
    storagetemperature: '-40 ~ 70°C',
    operatinghumidity: '5 ~ 95% (non-condensing)',
    power1: 'DC -48VDC',
    power2: 'AC: 220VAC',
    poweroptical: '',
    powercomsumptions: '265W (PSU DC) 310W (PSU AC)',
    dimensions: '482.6 x 133 x 280 mm (3RU, Wing Bracket included)',
    networkdiagram: '',
  },
  {
    id: '3',
    module: 'A',
    logo: 'https://ik.imagekit.io/iamfake/products/logo_card.png?updatedAt=1750092485669',
    image: 'https://ik.imagekit.io/iamfake/products/olt-v6016xc.png?updatedAt=1750091717062',
    category: 'XGSPON',
    subCategory: 'OLT',
    title: 'V6016XC',
    subtitle: 'XGSPON OLT',
    spec1: '16p GPON/XGSPON Combo',
    spec2: '4p 1/10/25GE',
    spec3: '2p 100GE',
    spec4: 'AC/DC',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions:
      'The XGS-PON technology adds new features and function­ality targeted at improving performance and interoper­ability, and adds support for new applications, services, and deployment scenarios. Among these changes are improvements in data rate and reach performance, dia­gnostics, and stand-by mode, to name a few. The V6016XC introduces a point-to-multipoint concept with the XGS-PON technology, which enables a cost-effective FTTx service. The reason why XGS-PON is considered as a cost effective solution is its usage of a passive splitter rather than an active switching system. The V6016XC is comprised of 16-port XGS-PON/GPON combo interface for service interface and fixed 4-port 25GE interface and 2-port 100GE for uplink on the front panel. It offers usable interface to make up diversity network services. Therefore, depending on customer requirements, it can be configured with several Ethernet configurations.',
    fitur1: '900 Gbps switching capacity',
    fitur2: 'Redundant dual power supply unit (PSU)',
    fitur3: '16-port XGS-PON/GPON combo interfaces',
    fitur4: 'Fixed 4-port 25GE and 2-port 100GE interfaces',
    fitur5: 'Hot Swappable for all plug-in units (PSU and FAN)',
    fitur6: 'XGS-PON ODN class N1 compliant with ITU-T G.9807.1',
    fitur7: 'ITU-T G.984.4 ONT Management & Control Interface (OMCI)',
    fitur8: 'GPON SFP B+, C+ compliant with ITU-T G.984.2',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '8MB(Boot) + 512MB(NOS) + 8GB(USB, Optional)',
    sdrammemory: '4GB',
    Interface1: '16 x XGS-PON/GPON combo (SFP+/SFP)',
    Interface2: '4 x 10/25GBase-R (SFP28)',
    Interface3: '2 x 40/100Base-R (QSFP28)',
    Interface4: '',
    Antena: '',
    operatingtemperature: '-40 ~ 65°C',
    storagetemperature: '-40 ~ 70°C',
    operatinghumidity: '5 ~ 95% (non-condensing)',
    power1: 'DC -48VDC',
    power2: 'AC: 100-240 VAC',
    poweroptical: '',
    powercomsumptions: 'Max. 230W (PSU DC) Max. 245W (PSU AC)',
    dimensions: '420 x 44 x 280 mm (1RU)',
    networkdiagram: '',
  },
  {
    id: '4',
    module: 'A',
    logo: 'https://ik.imagekit.io/iamfake/products/logo_card.png?updatedAt=1750092485669',
    image: 'https://ik.imagekit.io/iamfake/products/olt-v6008xc.png?updatedAt=1750154125972',
    category: 'XGSPON',
    subCategory: 'OLT',
    title: 'V6008XC',
    subtitle: 'XGSPON OLT',
    spec1: '8p GPON/XGSPON Combo',
    spec2: '4p 1/10/25GE',
    spec3: '2p 100GE',
    spec4: 'AC/DC',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions:
      'The XGS-PON technology adds new features and function­ality targeted at improving performance and interoper­ability, and adds support for new applications, services, and deployment scenarios. Among these changes are improvements in data rate and reach performance, dia­gnostics, and stand-by mode, to name a few. The V6008XC introduces a point-to-multipoint concept with the XGS-PON technology, which enables a cost-effective FTTx service. The reason why XGS-PON is considered as a cost effective solution is its usage of a passive splitter rather than an active switching system. The V6008XC is comprised of 8-port XGS-PON/GPON combo interface for service interface and fixed 4-port 25GE interface and 2-port 100GE for uplink on the front panel. It offers usable interface to make up diversity network services. Therefore, depending on customer requirements, it can be configured with several Ethernet configurations.',
    fitur1: 'Redundant dual power supply unit (PSU)',
    fitur2: '8-port XGS-PON/GPON combo interfaces',
    fitur3: 'Fixed 4-port 25GE and 2-port 100GE interfaces',
    fitur4: 'Hot Swappable for all plug-in units (PSU and FAN)',
    fitur5: 'XGS-PON ODN class N1 compliant with ITU-T G.9807.1',
    fitur6: 'ITU-T G.984.4 ONT Management & Control Interface (OMCI)',
    fitur7: 'GPON SFP B+, C+ compliant with ITU-T G.984.2',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '8MB (Boot) + 512MB (NOS) + 8GB (USB, Optional)',
    sdrammemory: '4GB',
    Interface1: '8 x XGS-PON/GPON combo (SFP+/SFP)',
    Interface2: '4 x 10/25GBase-R (SFP28)',
    Interface3: '2 x 40/100Base-R (QSFP28)',
    Interface4: '',
    Antena: '',
    operatingtemperature: '-40 ~ 65°C',
    storagetemperature: '-40 ~ 70°C',
    operatinghumidity: '5 ~ 95% (non-condensing)',
    power1: 'DC -48VDC',
    power2: 'AC: 100-240 VAC',
    poweroptical: '',
    powercomsumptions: 'Max. 155W (PSU DC) Max. 170W (PSU AC)',
    dimensions: '440 x 44 x 280 mm (1RU)',
    networkdiagram: '',
  },
  {
    id: '5',
    module: 'B',
    logo: 'https://ik.imagekit.io/iamfake/products/logo_card.png?updatedAt=1750092485669',
    image: 'https://ik.imagekit.io/iamfake/products/ont-h840c.png?updatedAt=1750092487469',
    category: 'XGSPON',
    subCategory: 'ONT',
    title: 'H840C',
    subtitle: 'XGSPON ONT',
    spec1: '4 ports 10/100/1000Base-T (RJ45)',
    spec2: '1 ports 101GBase-T (RJ45)',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions:
      'The H840C optical network terminal (ONT) is targeted for all subscribers requiring multiple POTS and high-speed data interfaces in a cost-effective indoor housing. H840C support a standalone device and with fan-less design. Fully compliant with ITU-T G.9807 standards, H840C supports data rates of 10Gbps upstream and downstream. The ONU is provided with Class N1/N2 type PMD. With DNS leading-edge XGS-PON technology, users can enjoy bandwidth-intensive multimedia services such as real-time audio, and gaming much easier and faster than ever before. The H840C supports Dynamic Bandwidth Allocation (DBA) mechanism in compliance with ITU-T G.9807 with the OLT to optimize upstream bandwidth allocation among ONUs based on the service contracts and supports status reporting DBA in compliance with ITU-T Rec. G.9807.1.',
    fitur1: '1-port XGS-PON interface for uplink',
    fitur2: '1-port N-Base-T(1/2.5/5/10GBase-T) interface',
    fitur3: '4-port 10/100/1000GBase-T interfaces',
    fitur4: 'ITU-T G.9807 compliant XGS-PON ONT',
    fitur5: 'XGS-PON data rate of 10Gbps/10Gbps(US/DS)',
    fitur6: 'Advanced QoS & Network Management',
    fitur7: 'IEEE802.1D and IEEE802.1Q bridging',
    fitur8: 'Priority queues and scheduling on Upstream',
    fitur9: 'Activation with automatic discovered Serial Number and password',
    fitur10: 'Dying Gasp support',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '128MB',
    sdrammemory: '512MB (DDR)',
    Interface1: '1 x N Base-T(1/2.5/5/10Base-T) (RJ45)',
    Interface2: '4 x 10/100/1000Base-T (RJ45)',
    Interface3: '1 x XGS-PON (SC/APC)',
    Interface4: '',
    Antena: '',
    operatingtemperature: '0 ~ 45°C',
    storagetemperature: '',
    operatinghumidity: '20 ~ 90% (non-condensing)',
    power1: '12VDC 1.5A',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '160 x 39.5 x 150 mm',
    networkdiagram: '',
  },
  {
    id: '6',
    module: 'B',
    logo: 'https://ik.imagekit.io/iamfake/products/logo_card.png?updatedAt=1750092485669',
    image: 'https://ik.imagekit.io/iamfake/products/ont-h842.png?updatedAt=1750393481115',
    category: 'XGSPON',
    subCategory: 'ONT',
    title: 'H842',
    subtitle: 'XGSPON ONT',
    spec1: '1 ports 10/100/1000Base-T (RJ45)',
    spec2: '1 ports 101GBase-T (RJ45)',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions:
      'The H842 is a high-performance, XGS-PON compliant Optical Network Terminal (ONT) able to support service provider requirements for high-speed data and voice in a cost-effective design. The ONT is fully compliant with ITU-T G.9807.1 XGS-PON standard with integrated, on-board optics supporting 1270nm and 1577nm wavelengths with Class N1 type PMD optical receiver. With leading-edge XGS-PON technology, users can enjoy bandwidth intensive multimedia services such as real-time audio, and gaming much easier and faster than ever before. The H842 provides one XGS-PON interface, one 1/2.5/5/10GBase-T port and one 10/100/1000Base-T port. The ONT contains an integrated L2 switch supporting wire-speed L2 bridging.',
    fitur1: 'IPTV multicast, IGMPv2 and IGMPv3 services',
    fitur2: 'MTU jumbo frame 9216-byte support',
    fitur3: 'Any-port, Any-service data model',
    fitur4: 'Traffic management including Q-in-Q tagging, 802.1Q VLANs, multiple subscriber VLANs',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '128MB',
    sdrammemory: '256MB',
    Interface1: ' 1-port 10/100/1000Base-T (RJ-45)',
    Interface2: '1-port 10GBase-T (RJ45)',
    Interface3: ' 1-port XGS-PON',
    Interface4: '',
    Antena: '',
    operatingtemperature: '0 to 40 °C',
    storagetemperature: '',
    operatinghumidity: '5 to 90 % (non-condensing)',
    power1: '12VDC 1.5A',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '160 × 40 x 140 mm',
    networkdiagram: '',
  },
  {
    id: '7',
    module: 'D',
    logo: 'https://ik.imagekit.io/iamfake/products/logo_card.png?updatedAt=1750092485669',
    image:
      'https://ik.imagekit.io/iamfake/products/zaram-xgspon-gponstick.png?updatedAt=1750406138420',
    category: 'XGSPON',
    subCategory: 'XGSPON STICK',
    title: 'ZXOS11EPI',
    subtitle: 'XGSPON STICK',
    spec1: '10 GPON Port (SC/UPC, SFP compliant interface)',
    spec2: 'SFP+ XFI interface',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: 'XGSPON chip and optical component integrated SFP+ ONU product',
    fitur1: 'Low Power Consumption SFP+ Formfactor with Embedded ZX300 SoC',
    fitur2: 'Compliant with standard SFP+ form factor SFF-8431, SFF-8472, GR-468',
    fitur3: 'XGS-PON uplink, G.9807 series and G.988 GPON OMCI compliant',
    fitur4: 'Very low power consumption, typically less than 2W',
    fitur5: 'SFF-8472 DDM',
    fitur6: 'Class N1/N2',
    fitur7: 'APD Receiver : -28.5dBm',
    fitur8: '1270nm DFB Burst Laser',
    fitur9: 'Commercial/Industrial Temperature',
    fitur10: 'IEEE 1588, ToD, SyncE Support(Only EPI supports SyncE)',
    fitur11: '10G XFI Interface',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: 'Embedded 256Mbit (Serial Flash*1)',
    sdrammemory: '',
    Interface1: 'Embedded 512Mbit, LPDDR"',
    Interface2: '10 GPON Port (SC/UPC, SFP compliant interface)',
    Interface3: 'SFP+ XFI interface',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '+4.0 ~ +9.0dBm',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '8',
    module: 'A',
    logo: 'https://ik.imagekit.io/iamfake/products/logo_card.png?updatedAt=1750092485669',
    image: 'https://ik.imagekit.io/iamfake/products/olt-V8106.png?updatedAt=1750091714706',
    category: 'GPON',
    subCategory: 'OLT',
    title: 'V8106',
    subtitle: 'GPON OLT',
    spec1: '96 GPON / 48 XG-PON',
    spec2: '6U chassis',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions:
      'The V8106 is a 6RU height chassis PON Optical Line Termination (OLT) supporting 96 GPON ports as well as a Layer 3 switch of supporting 8 1/10GbE ports Active Ethernet service. It terminates the traffic coming from the subscriber lines and consolidates it on one or more Gigabit Ethernet interfaces towards the metropolitan area. ',
    fitur1: 'Shelf with 6/2 slots for SIUs/NIUs for a maximum of interfaces per shelf',
    fitur2: '640Gbps switching capacity per unit',
    fitur3: 'Dual switch fabric units (SFU)',
    fitur4: 'Redundant and load-balanced dual power supply unit (PSU)',
    fitur5: 'Hot Swappable for all plug-in units (SFU, SIU, NIU, PSU, FAN)',
    fitur6: 'LED alarm indicator',
    fitur7: 'Visible alarm indicator',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '36MB (Dual OS)',
    sdrammemory: '2GB DDR3',
    Interface1: '16-port GPON interface Unit x6',
    Interface2: '4-port 10GBase-R interface Unit x2',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '-25 to 55°C (-13 to 131°F)',
    storagetemperature: '−40 to 80 °C (-40 to 176°F) ',
    operatinghumidity: '0 to 90 % (non-condensing',
    power1: '−48/60VDC ',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '482.6mm x 265.9mm x 280mm',
    networkdiagram: '',
  },
  {
    id: '9',
    module: 'A',
    logo: 'https://ik.imagekit.io/iamfake/products/logo_card.png?updatedAt=1750092485669',
    image: 'https://ik.imagekit.io/iamfake/products/olt-V8102.png?updatedAt=1750160493023',
    category: 'GPON',
    subCategory: 'OLT',
    title: 'V8102',
    subtitle: 'GPON OLT',
    spec1: '32-Port GPON',
    spec2: '2RU height chassis',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions:
      'DASAN Networks V8106 is a chassis system. DASAN Networks V8102 is a 2RU GPON OLT chassis system consisting of 4 slots for 2 modular service slots, 2 fabric switching slots and 2 uplink slots to provide complete features and high performance for FTTx applications. The V8102 OLT is a high-density chassis system that supports up to 4096 residential and business customers with 32 GPON ports (1:128 split ratio). The V8102 GPON OLT supports redundant GPON systems. The V8102 features high-capacity GPON access capacity and 10GbE uplink and line rate performance with non-blocked 320Gbps switch fabric. In addition, V8102 is ready for XG-PON service, it fully supports XG-PON technology with the same chassis. V8102 ensures equipment-level reliability with full redundancy design concept for SFU/Power/GPON units. PON technology adds new features and functionalities targeted to improve performance and interoperability, and adds support for new applications, services, and deployment scenarios.',
    fitur1: '320Gbps switching capacity',
    fitur2: '2-Slot for switching fabric unit + uplink interface units',
    fitur3: '2-Slot for subscriber interface units (SIUs)',
    fitur4: 'Redundant and load-balanced dual power supply unit (PSU)',
    fitur5: 'Hot swappable FAN unit',
    fitur6: 'LED alarm indicator',
    fitur7: 'Visible alarm indicator',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '8MB Boot, 64MB NOS (dual) ',
    sdrammemory: '2GB (DDR3)',
    Interface1: '2x 16-port of GPON interfaces (SIU_GPON16)',
    Interface2: '4-port of 1G/10GBase-R optical interfaces (SFP/SFP+)',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '5~131°F (-15~55°C) ',
    storagetemperature: '-40~158°F (-40~70°C)',
    operatinghumidity: '0 to 90 % (non-condensing)',
    power1: 'DC type: −48/60V ',
    power2: '',
    poweroptical: '',
    powercomsumptions: 'Approximately 206 W',
    dimensions: '297 mm x 20.5 mm x 252.5 mm',
    networkdiagram: '',
  },
  {
    id: '10',
    module: 'A',
    logo: 'https://ik.imagekit.io/iamfake/products/logo_card.png?updatedAt=1750092485669',
    image: 'https://ik.imagekit.io/iamfake/products/olt-V5816.png?updatedAt=1750160494148',
    category: 'GPON',
    subCategory: 'OLT',
    title: 'V5816',
    subtitle: 'GPON OLT',
    spec1: '16p GPON',
    spec2: '4p 1/10GE',
    spec3: 'AC/DC',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions:
      'As the number of services using internet communications such as broadband internet, internet telephony, and IPTV increases, the need for high-performance network equipment is increasing. This is no exception in areas where population density is low and where there are few customers. You can plan more effectively in terms of network deployment costs. The V5816 is a compact GPON OLT system with 16 GPON ports, 4 1G/10GBase-R ports for uplink, and 4 1000Base-T ports, making it suitable for low-density and low-cost FTTx services. V5816 supports Gigabit ports and is applicable to various network environments. In addition, the redundant power supply is realized so that the network system is not interrupted, ensuring stable service.',
    fitur1: '168 Gbps switching capacity',
    fitur2: '16 GPON ports, 4 10GE ports and 4 GE (Electric)  ports',
    fitur3: 'Reliable FTTx service with power redundancy system',
    fitur4: 'Enhanced QoS services',
    fitur5: 'IGMP support for IPTV',
    fitur6: 'Fully Managed via Dasan’s INAS Element Manager',
    fitur7: 'Increased reliability through power redundancy',
    fitur8: 'Comfortable network management with SNMPv2 / v3 and RMON',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '1GB (DDR3)',
    Interface1: '16-Port GPON (SFP)',
    Interface2: '4-Port 100/1000Base-T (RJ45)',
    Interface3: '4-Port 1G/10GBase-R (SFP/SFP+)',
    Interface4: '',
    Antena: '',
    operatingtemperature: '-20~60°C',
    storagetemperature: '',
    operatinghumidity: '0~90% (non-condensing)',
    power1: 'DC type : -48/60VDC',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '440 x 44 x 300mm',
    networkdiagram: '',
  },
  {
    id: '11',
    module: 'A',
    logo: 'https://ik.imagekit.io/iamfake/products/logo_card.png?updatedAt=1750092485669',
    image: 'https://ik.imagekit.io/iamfake/products/olt-V5808.png?updatedAt=1750160493762',
    category: 'GPON',
    subCategory: 'OLT',
    title: 'V5808',
    subtitle: 'GPON OLT',
    spec1: '8p GPON',
    spec2: '4p 1/10GE',
    spec3: 'AC/DC',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions:
      'As the number of services using internet communications such as broadband internet, internet telephony, and IPTV increases, the need for high-performance network equipment is increasing. This is no exception in areas where population density is low and where there are few customers. You can plan more effectively in terms of network deployment costs. The V5808 is a compact GPON OLT system with 8 GPON ports, 4 1G/10GBase-R ports for uplink, and 4 1000Base-T ports, making it suitable for low-density and low-cost FTTx services. V5808 supports Gigabit ports and is applicable to various network environments. In addition, the power supply that supports redundant has been realized so that the network system is not disturbed, ensuring stable service.',
    fitur1: '8 GPON ports, 10GE 4 ports and GE (Electric) 4 ports',
    fitur2: '118 Gbps switching capacity',
    fitur3: 'High Capacity Uplink / Service Interface 2.5Gbps (down) / 1.25Gbps (up)',
    fitur4: 'Reliable FTTx service with power redundancy system',
    fitur5: 'Enhanced QoS services',
    fitur6: 'Fully Managed via Dasan’s INAS Element Manager',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '1GB (DDR3)',
    Interface1: '8 GPON(SFP, SC/PC type)',
    Interface2: '4-Port 100/1000Base-T (RJ45)',
    Interface3: '4-Port 1G/10GBase-R (SFP/SFP+)',
    Interface4: '',
    Antena: '',
    operatingtemperature: '-20~60°C',
    storagetemperature: '',
    operatinghumidity: '0~90% (non-condensing)',
    power1: 'DC type : -48/60VDC',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '440 x 44 x 300mm',
    networkdiagram: '',
  },
  {
    id: '12',
    module: 'B',
    logo: 'https://ik.imagekit.io/iamfake/products/logo_card.png?updatedAt=1750092485669',
    image: 'https://ik.imagekit.io/iamfake/products/onu-d2224gp.png?updatedAt=1750092496705',
    category: 'GPON',
    subCategory: 'ONU PoE',
    title: 'D2224GP',
    subtitle: 'ONU PoE',
    spec1:
      'Supports PoE power up to 30W for each PoE port, total power up to 370W for all PoE ports',
    spec2: '24 10/100/1000Mbps Auto MDI/MDI-X Ethernet port (4 SFP combo ports)',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions:
      "D2224GP is a high performance the second managed gigabit switch. Provides twenty-four 10/100/1000Mbps self-adaption RJ45 ports, plus four  gigabit  SFP ports, it can be used to link bandwidth higher upstream equipment. Support VLAN ACL based on port, easily implement network monitoring, traffic regulation, priority tag and traffic control. Support traditional STP/RSTP/MSTP 2 link protection technology; greatly improve the ability of fault tolerance, redundancy backup to ensure the stable operation of the network. D2224GP provides perfect QOS strategy and plenty of VLAN function. Support 802. 1x authentication based on the port and MAC, easily set user access. Support ACL control based on the time, easy control the access time accurately. D2224GP's PoE ports can automatically detect and supply power with those IEEE 802.3at/af compliant Powered Devices (PD). In this situation, the electrical power is transmitted along with data in one single cable allowing you to expand your network where there are no power lines or outlets, where you wish to fix devices such as AP, IP Cameras or IP Phones, etc",
    fitur1: '24 10/100/1000Mbps Auto MDI/MDI-X Ethernet port (4 SFP combo ports)',
    fitur2: 'Switching Capacity up to 56Gbps',
    fitur3: 'Store and forward mode operates',
    fitur4: 'Support Web-based Management ',
    fitur5:
      'Supports PoE power up to30W for each PoE port, total power up to 370W for all PoE ports',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '24 port 10/100/1000Mbps PoE/PoE+',
    Interface2: '4 ports 2 x100/1000Mbps SFP port',
    Interface3: 'H650SFP : uplink GPON ',
    Interface4: '',
    Antena: '',
    operatingtemperature: '0 to 60°C',
    storagetemperature: '',
    operatinghumidity: '10 to 90% (non-condensing)',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '< 22W (without POE), < 400W (with POE)',
    dimensions: '440mm x 44mm x 208mm',
    networkdiagram: '',
  },
  {
    id: '13',
    module: 'B',
    logo: 'https://ik.imagekit.io/iamfake/products/logo_card.png?updatedAt=1750092485669',
    image: 'https://ik.imagekit.io/iamfake/products/l2-d2008gpe.png?updatedAt=1750233558797',
    category: 'GPON',
    subCategory: 'ONU PoE',
    title: 'D2008GPE',
    subtitle: 'ONU PoE',
    spec1: 'Supports PoE power up to 30W for each PoE port',
    spec2: 'Total power up to 150W for all PoE ports',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions:
      'D2008GPE is a new generation designed for high security and high-performance network the layer 2 switch. Provides eight 10/100/1000Mbps self-adaption RJ45 port, and two 100/1000Mbps SFP ports, all ports support wire-speed forwarding, can provide you with larger network flexibility. All ports support Auto MDI/MDIX function.The Switch with a low-cost, easy-to-use, high performance upgrade your old network to a 1000Mbps Gigabit network. ',
    fitur1: 'Switching Capacityup to 20Gbps',
    fitur2: 'Supports PoE power up to 30W for each PoE port',
    fitur3: 'Total power up to 150W for all PoE ports',
    fitur4: 'Support web management',
    fitur5: 'High performance, durable stability',
    fitur6: 'Intelligent identification',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '8 x 10/100/1000Mbps Auto-Negotiation ports',
    Interface2: '2 ports 2 x100/1000Mbps SFP port',
    Interface3: 'H650SFP : uplink GPON ',
    Interface4: '',
    Antena: '',
    operatingtemperature: '0 to 50°C',
    storagetemperature: '',
    operatinghumidity: '10 to 90% (non-condensing)',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: 'Less than 140W (at PoE full-load)',
    dimensions: '280 x 44 x 180mm',
    networkdiagram: '',
  },
  {
    id: '14',
    module: 'B',
    logo: 'https://ik.imagekit.io/iamfake/products/logo_card.png?updatedAt=1750092485669',
    image: 'https://ik.imagekit.io/iamfake/products/D2224g.png?updatedAt=1750092485713',
    category: 'GPON',
    subCategory: 'ONU',
    title: 'D2224G',
    subtitle: 'ONU',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions:
      'D2224G Supports VLAN ACL based on port, easily implement network monitoring, traffic regulation, priority tag and traffic control. Support traditional STP/RSTP/MSTP2 link protection technology; greatly improve the ability of fault tolerance, redundancy backup to ensure the stable operation of the network. Support ACL control based on the time, easy control the access time accurately. Support 802.1x authentication based on the port and MAC, easily set user access. ',
    fitur1: 'Switching Capacity up to 56Gbps',
    fitur2: 'Store and forward mode operation',
    fitur3: 'Support Web-based Management ',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '24 port 10/100/1000Base-T (RJ45)',
    Interface2: '4 ports 100/1000Base-SFP',
    Interface3: 'H650SFP : uplink GPON ',
    Interface4: '',
    Antena: '',
    operatingtemperature: '0℃ - 45℃',
    storagetemperature: '',
    operatinghumidity: '10 to 90% (non-condensing)',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: 'Maximum:20W(220V/50Hz)',
    dimensions: '440 x 44 x 208mm',
    networkdiagram: '',
  },
  {
    id: '15',
    module: 'A',
    logo: 'https://ik.imagekit.io/iamfake/products/logo_card.png?updatedAt=1750092485669',
    image: 'https://ik.imagekit.io/iamfake/products/l2-v2724gt.png?updatedAt=1750247607040',
    category: 'GPON',
    subCategory: 'ONU',
    title: 'V2724GT',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions:
      'The V2724GT is a cost effective single-board Gigabit Ethernet switch. It has been designed as ultra-compact customer premise equipment with the reliable Layer 2 functionalities. The V2724GT is comprised of 24-port 10/100/1000Base-T(RJ45) and 4-port 10GBase-R(SFP /SFP+). The MGMT and console interface is also located on the front panel with embedded LED for LNK/ACT and TX/RX indication respectively. They are for use of equipment management via remote access or CLI. The V2724GT provides a single AC/DC power connector input and its switch on the front panel. This system supports PSU (AC/DC) and fixed FANs for stable service delivery.',
    fitur1: '128Gbps switching capacity',
    fitur2: '95Mpps Throughput',
    fitur3: '24-port 1 Gibabit Ethernet',
    fitur4: '4-port 10 Gigabit Ethernet',
    fitur5: 'Extensive Layer2 access switch functions with non-blocking',
    fitur6:
      'Compact 1 RU chassis suitable for indoor and outdoor deployments, with AC & DC variants',
    fitur7: 'Management via CLI or SNMPv2/v3, plus NETCONF/YANG enabled for SDN network',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '512MB',
    sdrammemory: '512MB',
    Interface1: '24 x 10/100/1000Base-T (RJ45)',
    Interface2: '4 x 10GBase-R (SFP/SFP+)',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '-20 ~ 60°C',
    storagetemperature: '-40 ~ 70°C',
    operatinghumidity: '0 ~ 90% (non-condensing)',
    power1: 'DC 48VDC',
    power2: 'AC: 100~230VAC',
    poweroptical: '',
    powercomsumptions: '27W',
    dimensions: '440 x 44 x 240 mm',
    networkdiagram: '',
  },
  {
    id: '16',
    module: 'B',
    logo: 'https://ik.imagekit.io/iamfake/products/logo_card.png?updatedAt=1750092485669',
    image: 'https://ik.imagekit.io/iamfake/products/ont-h660nb.png?updatedAt=1750092487672',
    category: 'GPON',
    subCategory: 'ONT',
    title: 'H660NB',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions:
      'The H660NB is GPON Optical Network Terminal (ONT) compliant with ITU-T G.984 standard. The H660NB is developed for all clients based on GPON technology. GPON technology supports upstream 1.25Gbps and downstream 2.5Gbps data transmission rate. With DNS leading-edge GPON technology, users can enjoy band­width consuming multimedia services such as real-time video, audio and gaming much easier and faster than ever before. The H660NB is comprised of 1 GPON uplink port and 4 Gigabit Ethernet downlink port supporting 10/100/ 500/1000Base-T (RJ45). The H660NB supports high speed internet access service. The H660NB contains both built-in wire-speed L2 switch and L3 routing gateway with port forwarding, NAT and NAPT address translation, multiple PPPoE clients support for high speed internet service.',
    fitur1: '1-port GPON interface for uplink',
    fitur2: '4-port 10/100/500/1000Base-T interface',
    fitur3: 'ITU-T G.984.x compliant GPON ONT',
    fitur4: 'GPON data rate of 1.2Gbps/2.5Gbps(US/DS)',
    fitur5: 'Advanced QoS & Network Management',
    fitur6: 'Protection of delay-sensitive traffic based on SLA',
    fitur7: 'Multi-Layer Filtering',
    fitur8: 'Remote Fault monitoring',
    fitur9: 'IEEE 802.1D and IEEE 802.1Q bridging',
    fitur10: 'Dying Gasp support',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '128MB',
    sdrammemory: '128MB (DDR)',
    Interface1: '4 x 10/100/500/1000Base-T (RJ45)',
    Interface2: '1 x GPON (SC/APC)',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '-5 ~ 50°C',
    storagetemperature: '',
    operatinghumidity: '0 ~ 95% (non-condensing)',
    power1: '5VDC 2A',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '180 x 131 x 28 mm (Foot exluded)',
    networkdiagram: '',
  },
  {
    id: '17',
    module: 'C',
    logo: 'https://ik.imagekit.io/iamfake/products/logo_card.png?updatedAt=1750092485669',
    image: 'https://ik.imagekit.io/iamfake/products/ont-h660-gma.png?updatedAt=1750262804701',
    category: 'GPON',
    subCategory: 'ONT',
    title: 'H660GMA',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions:
      'H660GM-A optical network terminal (ONT) is targeted for all subscribers requiring high-speed data interfaces in a cost-effective indoor housing. Fully compliant with ITU-T G.984 standards, the H660GM-A supports data rates of 1.25Gbps upstream and 2.5Gbps downstream. The H660GM-A provides 1 GPON uplink port, 4 Gigabit Ethernet (10/100/1000Base-T) ports, Wireless LAN interface, and 1 FXS voice port that enhance the ability to deliver demanding data/Wi-Fi/VoIP services. The H660GM-A contains both built-in wire-speed L2 switch and L3 routing gateway with port forwarding, NAT and NAPT address translation, PPPoE client support for high speed Internet service.',
    fitur1: '1-port GPON interface for uplink',
    fitur2: '4-port 10/100/1000Base-T interface',
    fitur3: ' 1-port FXS interface for phone service',
    fitur4: 'ITU-T G.984.x compliant GPON ONT',
    fitur5: 'GPON data rate of 1.2Gbps/2.5Gbps(US/DS)',
    fitur6: 'SIP (RFC3261/3262/3264)',
    fitur7: 'Advanced QoS & Network Management',
    fitur8: 'Multi-Layer Filtering',
    fitur9: 'Remote Fault monitoring',
    fitur10: 'IEEE 802.1D and IEEE 802.1Q bridging',
    fitur11: 'Dying Gasp support',
    fitur12: 'IEEE802.11b/g/n/ac compliant',
    fitur13: 'Wi-Fi Max Throughput',
    fitur14: '300Mbps in 802.11n',
    fitur15: '866Mbps in 802.11ac',
    switchingcapacity: '',
    flashmemory: '128MB',
    sdrammemory: '256MB (DDR)',
    Interface1: '4 x 10/100/1000Base-T (RJ45)',
    Interface2: '1 x GPON (SC/APC)',
    Interface3: '1 x FXS interface (RJ11)',
    Interface4: '1 x USB 2.0 (Type A)',
    Antena: '2Tx2R, MIMO',
    operatingtemperature: '-5 ~ 45°C',
    storagetemperature: '',
    operatinghumidity: '20 ~ 90% (non-condensing)',
    power1: '12VDC 1.0A',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '160 x 40 x 140 mm (Antenna excluded) 212.6 x 186.5 x 140 mm (Antenna included)',
    networkdiagram: '',
  },
  {
    id: '18',
    module: 'C',
    logo: 'https://ik.imagekit.io/iamfake/products/logo_card.png?updatedAt=1750092485669',
    image: 'https://ik.imagekit.io/iamfake/products/ont-h660-gm.png?updatedAt=1750092485700',
    category: 'GPON',
    subCategory: 'ONT',
    title: 'H660GM',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions:
      'The H660GM provides one GPON uplink port, four Gigabit Ethernet (10/100/1000Base-T) ports, Wireless LAN interface and two FXS voice ports that enhance the ability to deliver demanding data/Wi-Fi/VoIP services. The H660GM uses Session Initiation Protocol (SIP) to terminate VoIP calls so that in-home wiring does not change and standard telephone setsmay be used. The H660GM supports the full triple play of services including voice and highspeed Internet access services.',
    fitur1: '',
    fitur2: '4-port 10/100/1000Base-T interface',
    fitur3: ' 2-port FXS interface for phone service',
    fitur4: 'ITU-T G.984.x compliant GPON ONT',
    fitur5: 'GPON data rate of 1.2Gbps/2.5Gbps(US/DS)',
    fitur6: 'SIP (RFC3261/3262/3264)',
    fitur7: 'Advanced QoS & Network Management',
    fitur8: 'Multi-Layer Filtering',
    fitur9: 'Remote Fault monitoring',
    fitur10: 'IEEE 802.1D and IEEE 802.1Q bridging',
    fitur11: 'Dying Gasp support',
    fitur12: 'IEEE802.11b/g/n/ac compliant',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '128MB',
    sdrammemory: '128MB',
    Interface1: '4-port 10/100/1000Base-T (RJ-45)',
    Interface2: '1 x GPON (SC/APC)',
    Interface3: ' 2-port FXS (RJ-11)',
    Interface4: '',
    Antena: 'Wi-Fi 802.11b/g/n/ac, 4 antennas (2T2R)',
    operatingtemperature: '-5 to 50 °C',
    storagetemperature: '',
    operatinghumidity: '20 to 90 % (non-condensing)',
    power1: '12VDC 1.5A',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '212 × 40 x 140 mm',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
  {
    id: '',
    module: '',
    logo: '',
    image: '',
    category: '',
    subCategory: '',
    title: '',
    subtitle: '',
    spec1: '',
    spec2: '',
    spec3: '',
    spec4: '',
    spec5: '',
    spec6: '',
    spec7: '',
    descriptions: '',
    fitur1: '',
    fitur2: '',
    fitur3: '',
    fitur4: '',
    fitur5: '',
    fitur6: '',
    fitur7: '',
    fitur8: '',
    fitur9: '',
    fitur10: '',
    fitur11: '',
    fitur12: '',
    fitur13: '',
    fitur14: '',
    fitur15: '',
    switchingcapacity: '',
    flashmemory: '',
    sdrammemory: '',
    Interface1: '',
    Interface2: '',
    Interface3: '',
    Interface4: '',
    Antena: '',
    operatingtemperature: '',
    storagetemperature: '',
    operatinghumidity: '',
    power1: '',
    power2: '',
    poweroptical: '',
    powercomsumptions: '',
    dimensions: '',
    networkdiagram: '',
  },
])

// Tambahkan slug otomatis
products.value.forEach((product) => {
  product.slug = generateSlug(product.title)
})

export default products

export function useProductBySlug(slug) {
  return products.value.find((p) => p.slug === slug)
}
